In [1]:
import os

dataset_path = "/kaggle/input"

csv_files = []

for root, dirs, files in os.walk(dataset_path):
    for file in files:
        if file.endswith(".csv"):
            csv_files.append(os.path.join(root, file))

print("CSV files found:")

for i, file in enumerate(csv_files):
    print(f"{i}: {file}")

CSV files found:
0: /kaggle/input/datasets/ajverse/customer-support-tickets-crm-dataset/customer_support_tickets.csv
1: /kaggle/input/datasets/ajverse/customer-support-tickets-crm-dataset/enhanced_customer_support_data.csv

In [2]:
import os
import pandas as pd

dataset_path = "/kaggle/input"

csv_files = []

for root, dirs, files in os.walk(dataset_path):
    for file in files:
        if file.endswith(".csv"):
            csv_files.append(os.path.join(root, file))

print("CSV files found:")

for i, file in enumerate(csv_files):
    print(f"{i}: {file}")

CSV files found:
0: /kaggle/input/datasets/ajverse/customer-support-tickets-crm-dataset/customer_support_tickets.csv
1: /kaggle/input/datasets/ajverse/customer-support-tickets-crm-dataset/enhanced_customer_support_data.csv

In [3]:
import os
import pandas as pd

# Find CSV files
csv_files = []

for root, dirs, files in os.walk("/kaggle/input"):
    for file in files:
        if file.endswith(".csv"):
            csv_files.append(os.path.join(root, file))

if not csv_files:
    print("No CSV files found. Check whether the dataset is attached.")
else:
    print("Available CSV files:")
    for i, path in enumerate(csv_files):
        print(f"{i}: {path}")

    # Load the first CSV file
    df = pd.read_csv(csv_files[0])

    print("\nDataset shape:", df.shape)
    print("\nColumn names:")
    print(df.columns.tolist())

    print("\nFirst 5 rows:")
    display(df.head())

Available CSV files:
0: /kaggle/input/datasets/ajverse/customer-support-tickets-crm-dataset/customer_support_tickets.csv
1: /kaggle/input/datasets/ajverse/customer-support-tickets-crm-dataset/enhanced_customer_support_data.csv

Dataset shape: (20000, 12)

Column names:
['Ticket_ID', 'Customer_Name', 'Customer_Email', 'Ticket_Subject', 'Ticket_Description', 'Issue_Category', 'Priority_Level', 'Ticket_Channel', 'Submission_Date', 'Resolution_Time_Hours', 'Assigned_Agent', 'Satisfaction_Score']

First 5 rows:

,Ticket_ID,Customer_Name,Customer_Email,Ticket_Subject,Ticket_Description,Issue_Category,Priority_Level,Ticket_Channel,Submission_Date,Resolution_Time_Hours,Assigned_Agent,Satisfaction_Score
0,TKT-100000,George Simon,lisastrickland@example.com,Hours of operation - Individual,"Hi Support, Where is your headquarters located...",General Inquiry,High,Web Form,2025-07-02,43,David Kim,5
1,TKT-100001,Scott Thompson,wevans@example.org,Data not syncing - Card,"Hi Support, The application crashes every time...",Technical,High,Chat,2025-06-28,41,Elena Rodriguez,5
2,TKT-100002,Jennifer Smith,oleonard@example.net,2FA issues - Question,"Hi Support, How do I upgrade to the Enterprise...",Account,High,Web Form,2025-02-05,7,Anya Sharma,5
3,TKT-100003,Rachel Bullock,katherine67@example.net,Login failed - Let,"Hi Support, The dashboard is not loading any d...",Technical,Low,Web Form,2025-03-20,41,Anya Sharma,5
4,TKT-100004,Thomas Parks DDS,raykelsey@example.com,Refund status - Attention,"Hi Support, I have been trying to update my pa...",Billing,Medium,Email,2025-04-27,40,David Kim,5

In [4]:
# Check dataset information
print("Dataset shape:", df.shape)

print("\nColumn names and data types:")
df.info()

print("\nMissing values in each column:")
display(df.isnull().sum().sort_values(ascending=False))

print("\nNumber of duplicate rows:", df.duplicated().sum())

Dataset shape: (20000, 12)

Column names and data types:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Ticket_ID              20000 non-null  object
 1   Customer_Name          20000 non-null  object
 2   Customer_Email         20000 non-null  object
 3   Ticket_Subject         20000 non-null  object
 4   Ticket_Description     20000 non-null  object
 5   Issue_Category         20000 non-null  object
 6   Priority_Level         20000 non-null  object
 7   Ticket_Channel         20000 non-null  object
 8   Submission_Date        20000 non-null  object
 9   Resolution_Time_Hours  20000 non-null  int64
 10  Assigned_Agent         20000 non-null  object
 11  Satisfaction_Score     20000 non-null  int64
dtypes: int64(2), object(10)
memory usage: 1.8+ MB

Missing values in each column:

Ticket_ID                0
Customer_Name            0
Customer_Email           0
Ticket_Subject           0
Ticket_Description       0
Issue_Category           0
Priority_Level           0
Ticket_Channel           0
Submission_Date          0
Resolution_Time_Hours    0
Assigned_Agent           0
Satisfaction_Score       0
dtype: int64

Number of duplicate rows: 0

In [5]:
# Display sample customer feedback from each text column
text_columns = df.select_dtypes(include=["object", "string"]).columns

for col in text_columns:
    print(f"\n{'=' * 60}")
    print(f"Column: {col}")
    print(df[col].dropna().astype(str).head(3).to_list())

============================================================
Column: Ticket_ID
['TKT-100000', 'TKT-100001', 'TKT-100002']

============================================================
Column: Customer_Name
['George Simon', 'Scott Thompson', 'Jennifer Smith']

============================================================
Column: Customer_Email
['lisastrickland@example.com', 'wevans@example.org', 'oleonard@example.net']

============================================================
Column: Ticket_Subject
['Hours of operation - Individual', 'Data not syncing - Card', '2FA issues - Question']

============================================================
Column: Ticket_Description
['Hi Support, Where is your headquarters located? Lay soon message show know main.', 'Hi Support, The application crashes every time I open the settings tab. Speech wall six hour book.', 'Hi Support, How do I upgrade to the Enterprise plan? Close stand street wear your her.']

============================================================
Column: Issue_Category
['General Inquiry', 'Technical', 'Account']

============================================================
Column: Priority_Level
['High', 'High', 'High']

============================================================
Column: Ticket_Channel
['Web Form', 'Chat', 'Web Form']

============================================================
Column: Submission_Date
['2025-07-02', '2025-06-28', '2025-02-05']

============================================================
Column: Assigned_Agent
['David Kim', 'Elena Rodriguez', 'Anya Sharma']

In [6]:
import pandas as pd

# Select the correct customer feedback column
TEXT_COLUMN = "Ticket_Description"

# Remove missing and empty feedback
df_clean = df.dropna(subset=[TEXT_COLUMN]).copy()

df_clean[TEXT_COLUMN] = df_clean[TEXT_COLUMN].astype(str).str.strip()
df_clean = df_clean[df_clean[TEXT_COLUMN] != ""]

# Remove duplicate feedback
df_clean = df_clean.drop_duplicates(subset=[TEXT_COLUMN]).reset_index(drop=True)

print("Original dataset size:", len(df))
print("Clean dataset size:", len(df_clean))
print("Feedback column:", TEXT_COLUMN)

print("\nSample customer feedback:")
display(df_clean[[TEXT_COLUMN, "Issue_Category", "Satisfaction_Score"]].head())

Original dataset size: 20000
Clean dataset size: 20000
Feedback column: Ticket_Description

Sample customer feedback:

,Ticket_Description,Issue_Category,Satisfaction_Score
0,"Hi Support, Where is your headquarters located...",General Inquiry,5
1,"Hi Support, The application crashes every time...",Technical,5
2,"Hi Support, How do I upgrade to the Enterprise...",Account,5
3,"Hi Support, The dashboard is not loading any d...",Technical,5
4,"Hi Support, I have been trying to update my pa...",Billing,5

In [7]:
# Select 20 records for initial LLM experiments
sample_size = min(20, len(df_clean))

df_sample = df_clean.sample(
    n=sample_size,
    random_state=42
).reset_index(drop=True)

# Create a sequential ID for each sampled ticket
df_sample["Sample_ID"] = range(1, len(df_sample) + 1)

print("Total cleaned records:", len(df_clean))
print("Records selected for LLM:", len(df_sample))

print("\nSample customer feedback:")
display(
    df_sample[
        ["Sample_ID", "Ticket_Description",
         "Issue_Category", "Satisfaction_Score"]
    ].head(5)
)

Total cleaned records: 20000
Records selected for LLM: 20

Sample customer feedback:

,Sample_ID,Ticket_Description,Issue_Category,Satisfaction_Score
0,1,"Hi Support, I lost my phone and cannot pass th...",Account,4
1,2,"Hi Support, We are receiving a 500 Internal Se...",Technical,4
2,3,"Hi Support, The application crashes every time...",Technical,4
3,4,"Hi Support, I requested a refund 5 days ago, w...",Billing,1
4,5,"Hi Support, My data hasn't synced to the cloud...",Technical,5

In [8]:
%pip install -q transformers sentencepiece accelerate

Note: you may need to restart the kernel to use updated packages.

In [9]:
import torch
import transformers
import sentencepiece

print("PyTorch:", torch.__version__)
print("Transformers:", transformers.__version__)
print("GPU available:", torch.cuda.is_available())

print("\nAll required libraries imported successfully!")

PyTorch: 2.11.0+cpu
Transformers: 5.16.1
GPU available: False

All required libraries imported successfully!

In [10]:
import torch
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

MODEL_NAME = "google/flan-t5-small"

# Load tokenizer
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

# Load pretrained language model
model = AutoModelForSeq2SeqLM.from_pretrained(MODEL_NAME)

# Use GPU if available; otherwise use CPU
device = "cuda" if torch.cuda.is_available() else "cpu"
model = model.to(device)

print("Model loaded successfully!")
print("Model:", MODEL_NAME)
print("Device:", device)

config.json:   0%|          | 0.00/1.40k [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

tokenizer_config.json:   0%|          | 0.00/2.54k [00:00<?, ?B/s]

spiece.model: reconstructing file:   0%|          |  0.00B /  792kB

spiece.model: downloading bytes:           |  0.00B

tokenizer.json:   0%|          | 0.00/2.42M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/2.20k [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  308MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/190 [00:00<?, ?it/s]

[transformers] The tied weights mapping and config for this model specifies to tie shared.weight to lm_head.weight, but both are present in the checkpoints with different values, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning.

generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

Model loaded successfully!
Model: google/flan-t5-small
Device: cpu

In [11]:
import pandas as pd
import torch
from tqdm.auto import tqdm

def summarize_feedback(text):
    prompt = (
        "Summarize the following customer support feedback "
        "in one short sentence:\n" + str(text)
    )

    inputs = tokenizer(
        prompt,
        return_tensors="pt",
        max_length=512,
        truncation=True
    ).to(device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=60,
            num_beams=4,
            do_sample=False
        )

    summary = tokenizer.decode(
        outputs[0],
        skip_special_tokens=True
    )

    return summary

# Generate summaries
summaries = []

for text in tqdm(df_sample[TEXT_COLUMN], desc="Summarizing tickets"):
    summaries.append(summarize_feedback(text))

df_sample["LLM_Summary"] = summaries

print("Original feedback and generated summaries:")
display(
    df_sample[
        ["Sample_ID", TEXT_COLUMN, "LLM_Summary"]
    ].head(10)
)

Summarizing tickets:   0%|          | 0/20 [00:00<?, ?it/s]

Original feedback and generated summaries:

,Sample_ID,Ticket_Description,LLM_Summary
0,1,"Hi Support, I lost my phone and cannot pass th...",I lost my phone and cannot pass the 2FA check....
1,2,"Hi Support, We are receiving a 500 Internal Se...",We are receiving a 500 Internal Server Error o...
2,3,"Hi Support, The application crashes every time...","Hi, I'm sorry to hear that. I'm sorry to hear ..."
3,4,"Hi Support, I requested a refund 5 days ago, w...",I'm not sure if it's a soldier kitchen tree in...
4,5,"Hi Support, My data hasn't synced to the cloud...",Thank you for your help. I'm sorry to hear tha...
5,6,"Hi Support, I have been trying to update my pa...",I have been trying to update my payment method...
6,7,"Hi Support, The application crashes every time...","Hi, I'm sorry to hear that. I'm sorry to hear ..."
7,8,"Hi Support, Why is my bill higher than the agr...",Your bill is higher than the agreed amount. Yo...
8,9,"Hi Support, The dashboard is not loading any d...","The dashboard is not loading any data, just a ..."
9,10,"Hi Support, We are receiving a 500 Internal Se...","Hi, I'm sorry to hear that. I'm sorry to hear ..."

In [12]:
def extract_topic(text):
    prompt = (
        "Identify the single main issue discussed in this customer "
        "support ticket. Return only a short topic label of 2 to 5 words.\n\n"
        "Customer ticket: " + str(text) + "\n\n"
        "Topic:"
    )

    inputs = tokenizer(
        prompt,
        return_tensors="pt",
        max_length=512,
        truncation=True
    ).to(device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=20,
            num_beams=4,
            do_sample=False
        )

    return tokenizer.decode(
        outputs[0],
        skip_special_tokens=True
    ).strip()


# Extract one topic per ticket
topics = []

for text in tqdm(df_sample[TEXT_COLUMN], desc="Extracting topics"):
    topics.append(extract_topic(text))

df_sample["LLM_Topic"] = topics

print("Extracted topics:")
display(
    df_sample[
        ["Sample_ID", TEXT_COLUMN, "LLM_Summary", "LLM_Topic"]
    ]
)

Extracting topics:   0%|          | 0/20 [00:00<?, ?it/s]

Extracted topics:

,Sample_ID,Ticket_Description,LLM_Summary,LLM_Topic
0,1,"Hi Support, I lost my phone and cannot pass th...",I lost my phone and cannot pass the 2FA check....,Customer support
1,2,"Hi Support, We are receiving a 500 Internal Se...",We are receiving a 500 Internal Server Error o...,Internal Server Error
2,3,"Hi Support, The application crashes every time...","Hi, I'm sorry to hear that. I'm sorry to hear ...","Support, The application crashes every time I ..."
3,4,"Hi Support, I requested a refund 5 days ago, w...",I'm not sure if it's a soldier kitchen tree in...,Customer support
4,5,"Hi Support, My data hasn't synced to the cloud...",Thank you for your help. I'm sorry to hear tha...,Science/Tech
5,6,"Hi Support, I have been trying to update my pa...",I have been trying to update my payment method...,Customer support
6,7,"Hi Support, The application crashes every time...","Hi, I'm sorry to hear that. I'm sorry to hear ...",Support
7,8,"Hi Support, Why is my bill higher than the agr...",Your bill is higher than the agreed amount. Yo...,Customer support
8,9,"Hi Support, The dashboard is not loading any d...","The dashboard is not loading any data, just a ...",Customer support
9,10,"Hi Support, We are receiving a 500 Internal Se...","Hi, I'm sorry to hear that. I'm sorry to hear ...",Internal Server Error
10,11,"Hi Support, I received a suspicious email clai...",Thank you for your help. I'm sorry to hear tha...,Support
11,12,"Hi Support, Is there a roadmap for new feature...",Is there a roadmap for new features this year?...,Customer support
12,13,"Hi Support, Can you send me the invoice for tr...",Is there anything else I can help you with?,Customer Support
13,14,"Hi Support, My profile picture is not updating...",Thank you for your help. I'm sorry to hear tha...,"Hi Support, My profile picture is not updating..."
14,15,"Hi Support, We are receiving a 500 Internal Se...",We are receiving a 500 Internal Server Error o...,Internal Server Error
15,16,"Hi Support, How does the team pricing tier wor...",How does the team pricing tier work?,Customer support
16,17,"Hi Support, I want to permanently delete my ac...",Relate coach alone region opportunity bill ahead,Relate coach alone region opportunity
17,18,"Hi Support, I requested a refund 5 days ago, w...",Is there anything else I can help you with? Is...,Customer support
18,19,"Hi Support, I lost my phone and cannot pass th...",I lost my phone and cannot pass the 2FA check.,Customer support
19,20,"Hi Support, I received a suspicious email clai...",I'm sorry to hear that. I'm sorry to hear that...,Support

In [13]:
def extract_topic(text):
    prompt = (
        "Identify the main issue in this customer support ticket. "
        "Return only a short topic label of 2 to 5 words.\n\n"
        "Customer ticket: " + str(text)
    )

    inputs = tokenizer(
        prompt,
        return_tensors="pt",
        max_length=512,
        truncation=True
    ).to(device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=20,
            num_beams=4,
            do_sample=False
        )

    return tokenizer.decode(
        outputs[0],
        skip_special_tokens=True
    ).strip()


from tqdm.auto import tqdm

df_sample["LLM_Topic"] = [
    extract_topic(text)
    for text in tqdm(
        df_sample[TEXT_COLUMN],
        desc="Extracting topics"
    )
]

display(
    df_sample[
        ["Sample_ID", TEXT_COLUMN, "LLM_Topic"]
    ]
)

Extracting topics:   0%|          | 0/20 [00:00<?, ?it/s]

,Sample_ID,Ticket_Description,LLM_Topic
0,1,"Hi Support, I lost my phone and cannot pass th...",i lost my phone and cannot pass the 2FA check....
1,2,"Hi Support, We are receiving a 500 Internal Se...","Hi Support, We are receiving a 500 Internal Se..."
2,3,"Hi Support, The application crashes every time...","Hi Support, The application crashes every time..."
3,4,"Hi Support, I requested a refund 5 days ago, w...","Hi Support, I requested a refund 5 days ago, w..."
4,5,"Hi Support, My data hasn't synced to the cloud...","Hi Support, My data hasn't synced to the cloud..."
5,6,"Hi Support, I have been trying to update my pa...",customer support
6,7,"Hi Support, The application crashes every time...","Hi Support, The application crashes every time..."
7,8,"Hi Support, Why is my bill higher than the agr...","Customer ticket: Hi Support, Why is my bill hi..."
8,9,"Hi Support, The dashboard is not loading any d...","Hi Support, The dashboard is not loading any d..."
9,10,"Hi Support, We are receiving a 500 Internal Se...","Hi Support, We are receiving a 500 Internal Se..."
10,11,"Hi Support, I received a suspicious email clai...","Support, I received a suspicious email claimin..."
11,12,"Hi Support, Is there a roadmap for new feature...","Hi Support, Is there a roadmap for new feature..."
12,13,"Hi Support, Can you send me the invoice for tr...",#99283? Next picture land commercial door option.
13,14,"Hi Support, My profile picture is not updating...","Hi Support, My profile picture is not updating"
14,15,"Hi Support, We are receiving a 500 Internal Se...","Hi Support, We are receiving a 500 Internal Se..."
15,16,"Hi Support, How does the team pricing tier wor...","Customer ticket: Hi Support, How does the team..."
16,17,"Hi Support, I want to permanently delete my ac...","Hi Support, I want to permanently delete my ac..."
17,18,"Hi Support, I requested a refund 5 days ago, w...","Hi Support, I requested a refund 5 days ago, w..."
18,19,"Hi Support, I lost my phone and cannot pass th...","Hi Support, I lost my phone and cannot pass th..."
19,20,"Hi Support, I received a suspicious email clai...",I received a suspicious email claiming to be s...

In [14]:
print("LLM-generated topics vs. original categories")

display(
    df_sample[
        ["Sample_ID", "Issue_Category", "LLM_Topic", "LLM_Summary"]
    ]
)

print("\nOriginal Issue Category Counts:")
display(df_sample["Issue_Category"].value_counts(dropna=False))

print("\nLLM-Generated Topic Counts:")
display(df_sample["LLM_Topic"].value_counts(dropna=False))

LLM-generated topics vs. original categories

,Sample_ID,Issue_Category,LLM_Topic,LLM_Summary
0,1,Account,i lost my phone and cannot pass the 2FA check....,I lost my phone and cannot pass the 2FA check....
1,2,Technical,"Hi Support, We are receiving a 500 Internal Se...",We are receiving a 500 Internal Server Error o...
2,3,Technical,"Hi Support, The application crashes every time...","Hi, I'm sorry to hear that. I'm sorry to hear ..."
3,4,Billing,"Hi Support, I requested a refund 5 days ago, w...",I'm not sure if it's a soldier kitchen tree in...
4,5,Technical,"Hi Support, My data hasn't synced to the cloud...",Thank you for your help. I'm sorry to hear tha...
5,6,Billing,customer support,I have been trying to update my payment method...
6,7,Technical,"Hi Support, The application crashes every time...","Hi, I'm sorry to hear that. I'm sorry to hear ..."
7,8,Billing,"Customer ticket: Hi Support, Why is my bill hi...",Your bill is higher than the agreed amount. Yo...
8,9,Technical,"Hi Support, The dashboard is not loading any d...","The dashboard is not loading any data, just a ..."
9,10,Technical,"Hi Support, We are receiving a 500 Internal Se...","Hi, I'm sorry to hear that. I'm sorry to hear ..."
10,11,Fraud,"Support, I received a suspicious email claimin...",Thank you for your help. I'm sorry to hear tha...
11,12,General Inquiry,"Hi Support, Is there a roadmap for new feature...",Is there a roadmap for new features this year?...
12,13,Billing,#99283? Next picture land commercial door option.,Is there anything else I can help you with?
13,14,Account,"Hi Support, My profile picture is not updating",Thank you for your help. I'm sorry to hear tha...
14,15,Technical,"Hi Support, We are receiving a 500 Internal Se...",We are receiving a 500 Internal Server Error o...
15,16,General Inquiry,"Customer ticket: Hi Support, How does the team...",How does the team pricing tier work?
16,17,Account,"Hi Support, I want to permanently delete my ac...",Relate coach alone region opportunity bill ahead
17,18,Billing,"Hi Support, I requested a refund 5 days ago, w...",Is there anything else I can help you with? Is...
18,19,Account,"Hi Support, I lost my phone and cannot pass th...",I lost my phone and cannot pass the 2FA check.
19,20,Fraud,I received a suspicious email claiming to be s...,I'm sorry to hear that. I'm sorry to hear that...

Original Issue Category Counts:

Issue_Category
Technical          7
Billing            5
Account            4
Fraud              2
General Inquiry    2
Name: count, dtype: int64

LLM-Generated Topic Counts:

LLM_Topic
Hi Support, We are receiving a 500 Internal Server Error on the API endpoint.                               3
i lost my phone and cannot pass the 2FA check. South would four collection trip base provide                1
Hi Support, The application crashes every time I open the settings tab. Window create break teacher.        1
Hi Support, I requested a refund 5 days ago, where is it? Herself near believe                              1
Hi Support, My data hasn't synced to the cloud for 24 hours. State                                          1
customer support                                                                                            1
Hi Support, The application crashes every time I open the settings tab. Also leg writer.                    1
Customer ticket: Hi Support, Why is my bill higher than the agreed amount?                                  1
Hi Support, The dashboard is not loading any data, just a spinning wheel. Director never look               1
Support, I received a suspicious email claiming to be support. Change social eight capital.                 1
Hi Support, Is there a roadmap for new features this year?                                                  1
#99283? Next picture land commercial door option.                                                           1
Hi Support, My profile picture is not updating                                                              1
Customer ticket: Hi Support, How does the team pricing tier work? Blood will question recent measure        1
Hi Support, I want to permanently delete my account and data. Relate coach alone region opportunity bill    1
Hi Support, I requested a refund 5 days ago, where is it? Long cup middle social                            1
Hi Support, I lost my phone and cannot pass the 2FA check. Still partner determine brother summer           1
I received a suspicious email claiming to be support. I received a suspicious email claiming                1
Name: count, dtype: int64

In [15]:
print("Available variables related to TF-IDF, topics, sentiment, and summaries:\n")

for name in sorted(globals()):
    if any(word in name.lower() for word in [
        "tfidf", "vectorizer", "topic", "cluster",
        "sentiment", "summary", "ari", "nmi", "spearman"
    ]):
        try:
            value = globals()[name]
            print(f"{name}: {type(value).__name__}")
        except Exception:
            pass

Available variables related to TF-IDF, topics, sentiment, and summaries:

extract_topic: function
summaries: list
summarize_feedback: function
topics: list

In [16]:
print("Notebook variable check:\n")

for name in sorted(globals()):
    if not name.startswith("_"):
        try:
            obj = globals()[name]
            if isinstance(obj, (pd.DataFrame, pd.Series)):
                print(f"{name}: {type(obj).__name__}, shape={obj.shape}")
            elif any(k in name.lower() for k in [
                "tfidf", "vector", "topic", "cluster",
                "sentiment", "summary", "ari", "nmi", "spearman"
            ]):
                print(f"{name}: {type(obj).__name__}")
        except Exception:
            pass

Notebook variable check:

df: DataFrame, shape=(20000, 12)
df_clean: DataFrame, shape=(20000, 12)
df_sample: DataFrame, shape=(20, 15)
extract_topic: function
summaries: list
summarize_feedback: function
topics: list

In [17]:
print("DATASET")
print("Total records:", len(df))
print("Clean records:", len(df_clean))

print("\nLLM SAMPLE")
print("Sample records:", len(df_sample))

print("\nAVAILABLE COLUMNS")
print(df_sample.columns.tolist())

print("\nTOPIC EXTRACTION")
print("Topics extracted:", len(topics))
print("Sample topics:", topics[:10])

print("\nSUMMARIZATION")
print("Summaries generated:", len(summaries))
print("Sample summaries:", summaries[:3])

print("\nSAMPLE RESULTS")
display(df_sample.head(5))

DATASET
Total records: 20000
Clean records: 20000

LLM SAMPLE
Sample records: 20

AVAILABLE COLUMNS
['Ticket_ID', 'Customer_Name', 'Customer_Email', 'Ticket_Subject', 'Ticket_Description', 'Issue_Category', 'Priority_Level', 'Ticket_Channel', 'Submission_Date', 'Resolution_Time_Hours', 'Assigned_Agent', 'Satisfaction_Score', 'Sample_ID', 'LLM_Summary', 'LLM_Topic']

TOPIC EXTRACTION
Topics extracted: 20
Sample topics: ['Customer support', 'Internal Server Error', 'Support, The application crashes every time I open the settings tab. Window create break teacher.', 'Customer support', 'Science/Tech', 'Customer support', 'Support', 'Customer support', 'Customer support', 'Internal Server Error']

SUMMARIZATION
Summaries generated: 20
Sample summaries: ['I lost my phone and cannot pass the 2FA check. South would four collection trip base provide.', 'We are receiving a 500 Internal Server Error on the API endpoint. Media say eye democratic ability draw.', "Hi, I'm sorry to hear that. I'm sorry to hear that. I'm sorry to hear that. I'm sorry to hear that. I'm sorry to hear that. I'm sorry to hear that. I'm sorry to hear that. I'"]

SAMPLE RESULTS

,Ticket_ID,Customer_Name,Customer_Email,Ticket_Subject,Ticket_Description,Issue_Category,Priority_Level,Ticket_Channel,Submission_Date,Resolution_Time_Hours,Assigned_Agent,Satisfaction_Score,Sample_ID,LLM_Summary,LLM_Topic
0,TKT-110650,Crystal Bennett,Eric.Pruitt@tech.io,Change email - Trial,"Hi Support, I lost my phone and cannot pass th...",Account,Low,Web Form,2025-02-09,5,David Kim,4,1,I lost my phone and cannot pass the 2FA check....,i lost my phone and cannot pass the 2FA check....
1,TKT-102041,Hannah Davis,elizabethbrown@example.org,API Error 500 - Style,"Hi Support, We are receiving a 500 Internal Se...",Technical,Low,Email,2024-05-03,11,Chloe Adams,4,2,We are receiving a 500 Internal Server Error o...,"Hi Support, We are receiving a 500 Internal Se..."
2,TKT-108668,Dr. Melinda Peck,waltersronald@example.org,Login failed - Speak,"Hi Support, The application crashes every time...",Technical,Low,Email,2025-08-16,4,Elena Rodriguez,4,3,"Hi, I'm sorry to hear that. I'm sorry to hear ...","Hi Support, The application crashes every time..."
3,TKT-101114,Calvin Bryan,rroman@example.org,Payment failed - Them,"Hi Support, I requested a refund 5 days ago, w...",Billing,Low,Email,2024-08-01,16,David Kim,1,4,I'm not sure if it's a soldier kitchen tree in...,"Hi Support, I requested a refund 5 days ago, w..."
4,TKT-113902,Victoria Marsh,David.Aguirre@tech.io,Login failed - Learn,"Hi Support, My data hasn't synced to the cloud...",Technical,Low,Web Form,2025-11-10,120,Ben Carter,5,5,Thank you for your help. I'm sorry to hear tha...,"Hi Support, My data hasn't synced to the cloud..."

In [18]:
import plotly.express as px

category_counts = df_clean["Issue_Category"].value_counts().reset_index()
category_counts.columns = ["Issue Category", "Number of Tickets"]

fig = px.bar(
    category_counts,
    x="Issue Category",
    y="Number of Tickets",
    title="Distribution of Customer Support Issues",
    color="Number of Tickets",
    text="Number of Tickets",
    template="plotly_white",
    hover_data={"Issue Category": True, "Number of Tickets": True}
)

fig.update_layout(
    xaxis_title="Issue Category",
    yaxis_title="Number of Tickets",
    xaxis_tickangle=-35,
    title_x=0.5
)

fig.show()

In [19]:
import plotly.express as px
from textblob import TextBlob

# Calculate sentiment from customer feedback
def get_sentiment(text):
    polarity = TextBlob(str(text)).sentiment.polarity

    if polarity > 0.05:
        return "Positive"
    elif polarity < -0.05:
        return "Negative"
    else:
        return "Neutral"

df_clean["Sentiment"] = df_clean["Ticket_Description"].apply(get_sentiment)

# Count sentiment categories
sentiment_counts = (
    df_clean["Sentiment"]
    .value_counts()
    .rename_axis("Sentiment")
    .reset_index(name="Number of Tickets")
)

# Create interactive donut chart
fig = px.pie(
    sentiment_counts,
    names="Sentiment",
    values="Number of Tickets",
    title="Customer Feedback Sentiment Distribution",
    hole=0.45,
    color="Sentiment",
    color_discrete_map={
        "Positive": "#22C55E",
        "Neutral": "#64748B",
        "Negative": "#EF4444"
    },
    template="plotly_white"
)

fig.update_traces(
    textposition="inside",
    textinfo="label+percent",
    hovertemplate="%{label}<br>Tickets: %{value}<br>Share: %{percent}<extra></extra>"
)

fig.update_layout(title_x=0.5)
fig.show()

print("Sentiment counts:")
display(sentiment_counts)

Sentiment counts:

  Sentiment  Number of Tickets
0   Neutral               9719
1  Positive               7901
2  Negative               2380

In [20]:
import plotly.express as px
import pandas as pd

# Check that topic extraction has been completed
if "LLM_Topic" not in df_sample.columns:
    print("LLM_Topic column not found. Run your topic extraction cell first.")
else:
    topic_counts = (
        df_sample["LLM_Topic"]
        .fillna("Unknown")
        .value_counts()
        .reset_index()
    )

    topic_counts.columns = ["Topic", "Number of Tickets"]

    fig = px.bar(
        topic_counts,
        x="Topic",
        y="Number of Tickets",
        title="Distribution of LLM-Extracted Customer Support Topics",
        color="Number of Tickets",
        text="Number of Tickets",
        template="plotly_white",
        hover_data=["Topic", "Number of Tickets"]
    )

    fig.update_layout(
        title_x=0.5,
        xaxis_title="Extracted Topic",
        yaxis_title="Number of Tickets",
        xaxis_tickangle=-35
    )

    fig.show()

    display(topic_counts)

                                                Topic  Number of Tickets
0   Hi Support, We are receiving a 500 Internal Se...                  3
1   i lost my phone and cannot pass the 2FA check....                  1
2   Hi Support, The application crashes every time...                  1
3   Hi Support, I requested a refund 5 days ago, w...                  1
4   Hi Support, My data hasn't synced to the cloud...                  1
5                                    customer support                  1
6   Hi Support, The application crashes every time...                  1
7   Customer ticket: Hi Support, Why is my bill hi...                  1
8   Hi Support, The dashboard is not loading any d...                  1
9   Support, I received a suspicious email claimin...                  1
10  Hi Support, Is there a roadmap for new feature...                  1
11  #99283? Next picture land commercial door option.                  1
12     Hi Support, My profile picture is not updating                  1
13  Customer ticket: Hi Support, How does the team...                  1
14  Hi Support, I want to permanently delete my ac...                  1
15  Hi Support, I requested a refund 5 days ago, w...                  1
16  Hi Support, I lost my phone and cannot pass th...                  1
17  I received a suspicious email claiming to be s...                  1

In [21]:
import plotly.express as px

# Count satisfaction scores
satisfaction_counts = (
    df_clean["Satisfaction_Score"]
    .value_counts()
    .sort_index()
    .reset_index()
)

satisfaction_counts.columns = [
    "Satisfaction Score",
    "Number of Tickets"
]

# Create an interactive bar chart
fig = px.bar(
    satisfaction_counts,
    x="Satisfaction Score",
    y="Number of Tickets",
    title="Customer Satisfaction Score Distribution",
    color="Satisfaction Score",
    text="Number of Tickets",
    template="plotly_white",
    hover_data=["Satisfaction Score", "Number of Tickets"]
)

fig.update_layout(
    title_x=0.5,
    xaxis_title="Customer Satisfaction Score",
    yaxis_title="Number of Tickets"
)

fig.show()

display(satisfaction_counts)

   Satisfaction Score  Number of Tickets
0                   1               1965
1                   2               1905
2                   3               2584
3                   4               6783
4                   5               6763

In [22]:
print("Checking topic-clustering results...\n")

for name in sorted(globals()):
    if any(word in name.lower() for word in [
        "cluster", "topic_labels", "kmeans",
        "tfidf", "topic_keywords", "ari", "nmi"
    ]):
        try:
            obj = globals()[name]
            print(f"{name}: {type(obj).__name__}")

            if hasattr(obj, "shape"):
                print("  Shape:", obj.shape)
        except Exception:
            pass

Checking topic-clustering results...

summaries: list
summarize_feedback: function

In [23]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import MiniBatchKMeans

# Prepare customer feedback
feedback = df_clean["Ticket_Description"].fillna("").astype(str)

# Convert feedback into TF-IDF features
vectorizer = TfidfVectorizer(
    stop_words="english",
    max_features=2000,
    ngram_range=(1, 2),
    min_df=2
)

tfidf_matrix = vectorizer.fit_transform(feedback)

print("TF-IDF matrix shape:", tfidf_matrix.shape)

# Discover 10 topics
kmeans = MiniBatchKMeans(
    n_clusters=10,
    random_state=42,
    n_init=10,
    batch_size=1024
)

df_clean["Topic_ID"] = kmeans.fit_predict(tfidf_matrix)

print("\nNumber of topics discovered:",
      df_clean["Topic_ID"].nunique())

print("\nFeedback count per topic:")
display(
    df_clean["Topic_ID"]
    .value_counts()
    .sort_index()
    .rename_axis("Topic_ID")
    .reset_index(name="Feedback_Count")
)

TF-IDF matrix shape: (20000, 2000)

Number of topics discovered: 10

Feedback count per topic:

   Topic_ID  Feedback_Count
0         0            1648
1         1            1053
2         2            8878
3         3             768
4         4            2620
5         5             993
6         6            1625
7         7             840
8         8             871
9         9             704

In [24]:

import pandas as pd

# Get the TF-IDF feature names
feature_names = vectorizer.get_feature_names_out()

# Extract top keywords for each cluster
topic_keywords = {}

for topic_id in range(10):
    # Get the cluster center
    center = kmeans.cluster_centers_[topic_id]

    # Find the top 10 keywords
    top_indices = center.argsort()[-10:][::-1]
    keywords = feature_names[top_indices]

    topic_keywords[topic_id] = list(keywords)

# Display keywords for each topic
topic_table = pd.DataFrame({
    "Topic_ID": list(topic_keywords.keys()),
    "Top_Keywords": [
        ", ".join(keywords)
        for keywords in topic_keywords.values()
    ]
})

display(topic_table)

   Topic_ID                                       Top_Keywords
0         0  receiving, support receiving, 500, 500 interna...
1         1  patch, support install, latest, patch windows,...
2         2  support, hi support, hi, team, higher, support...
3         3  keeps, trying, failing, trying update, keeps f...
4         4  data, loading data, spinning wheel, support da...
5         5  crashes time, crashes, settings tab, settings,...
6         6  account, resetting, log, log account, resettin...
7         7  new, support roadmap, roadmap, roadmap new, ne...
8         8  support requested, requested refund, refund da...
9         9  2fa, 2fa check, lost phone, lost, phone pass, ...

In [25]:
from textblob import TextBlob
import pandas as pd

# Calculate sentiment polarity
def get_sentiment(text):
    polarity = TextBlob(str(text)).sentiment.polarity

    if polarity > 0.05:
        return "Positive"
    elif polarity < -0.05:
        return "Negative"
    else:
        return "Neutral"

# Apply sentiment analysis to all cleaned feedback
df_clean["Sentiment"] = df_clean["Ticket_Description"].apply(get_sentiment)

# Calculate sentiment distribution
sentiment_counts = (
    df_clean["Sentiment"]
    .value_counts()
    .rename_axis("Sentiment")
    .reset_index(name="Number_of_Tickets")
)

print("Sentiment analysis completed!")
display(sentiment_counts)

print("\nSample results:")
display(
    df_clean[
        ["Ticket_Description", "Sentiment", "Satisfaction_Score"]
    ].head(5)
)

Sentiment analysis completed!

  Sentiment  Number_of_Tickets
0   Neutral               9719
1  Positive               7901
2  Negative               2380

Sample results:

,Ticket_Description,Sentiment,Satisfaction_Score
0,"Hi Support, Where is your headquarters located...",Positive,5
1,"Hi Support, The application crashes every time...",Neutral,5
2,"Hi Support, How do I upgrade to the Enterprise...",Neutral,5
3,"Hi Support, The dashboard is not loading any d...",Neutral,5
4,"Hi Support, I have been trying to update my pa...",Neutral,5